AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  InputTopicARN:
    Description: 'SNS Topic ARN, destination for CWP Alerts'
    Value:
      Ref: InputTopic
  QueueURL: 
    Description: 'SQS Queue URL'
    Value: 
      Ref: LogsQueue
  QueueARN: 
    Description: 'SQS Queue ARN'
    Value: 
      Fn::GetAtt: 
        - LogsQueue
        - Arn      
    
Parameters:
  S3BucketForLogging:
    Default: '<S3-Bucket-Name-Here>'
    Description: 'REQUIRED - Target S3 Bucket for Logs (e.g. MyS3BucketName).'
    Type: String
  LogFolderPrefix:
    Default: 'Radware-logs/CWP'
    Description: 'REQUIRED - Log Folder Prefix. Context: s3://S3BucketName/<Log-Folder-Prefix>/...'
    Type: String
  LogObjectPrefix:
    Default: 'CWPAlerts'
    Description: 'REQUIRED - Log Object Prefix. Context: <Log-File-Prefix>_YYYYMMDDTHHMMZ_<Alphanumeric-String>.json'
    Type: String
  GzipEnabled:
    Default: 'true'
    Description: 'REQUIRED - Enable/disable gzip compression of log files. true/false'
    Type: String
  CNPAccountId:
    Description: The automated response Radware account ID to send publish notifications to. specified at the portal under Settings -> Cloud Accounts -> (Automated response) Activate
    AllowedPattern: '[0-9]*'
    MinLength: '12'
    MaxLength: '12'
    Type: String
    Default: '438643506655'
    
Resources:
  InputTopic:
    Type: AWS::SNS::Topic
  InputTopicPolicy:
    Properties:
      PolicyDocument:
        Id: CwpSnsPolicy
        Statement:
        - Action: sns:Publish
          Effect: Allow
          Principal:
            #AWS: arn:aws:iam::342443945406:root
            AWS: !Join [ '' , [ 'arn:aws:iam::' , !Ref CNPAccountId , ':root'] ]
          Resource:
            Ref: InputTopic
          Sid: CwpSnsPolicy
        Version: '2012-10-17'
      Topics:
      - Ref: InputTopic
    Type: AWS::SNS::TopicPolicy
  LogsQueue:
    DependsOn: InputTopic
    Properties:
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 30
    Type: AWS::SQS::Queue
  LogsQueuePolicy:
    DependsOn:
      - LogsQueue
      - InputTopic
    Properties: 
      PolicyDocument:
        Id: "SQSPolicy"
        Statement:
        - Action:
          - sqs:*
          Effect: Allow
          Resource: 
            Fn::GetAtt: 
            - LogsQueue
            - Arn
          Condition:
            ArnEquals: 
              'aws:SourceArn': 
                Ref: InputTopic
          Principal: "*"
        Version: '2012-10-17'
      Queues:
        - Ref: LogsQueue
    Type: AWS::SQS::QueuePolicy
  SubscribeSQStoSNS:
    DependsOn: 
      - LogsQueue
      - InputTopic
    Properties:
      Endpoint: 
        Fn::GetAtt: 
        - LogsQueue
        - Arn
      Protocol: sqs
      TopicArn: 
        Ref: InputTopic
    Type: AWS::SNS::Subscription
  Solution:
    DependsOn: 
      - LogsQueue
    Properties:
      CodeUri: 
        Bucket: !Join [ '' , [ 'cnp-public-' , !Ref AWS::Region ] ]
          # If deploying CFT manually, replace this join with a string (e.g. "Bucket: my-custom-bucket-name"
        Key: 'radware_cwp_s3_logger/radware_cwp_s3_logger.zip'
        # Key is the name of the zip file which contains lambda_function.py
      Description: 'CWP-Alerts -> SNS -> SQS <- Lambda -> S3'
      Environment:
        Variables:
          s3_bucket_for_logging:
            Ref: S3BucketForLogging
          queue_url: 
            Ref: LogsQueue
          log_folder_prefix:
            Ref: LogFolderPrefix
          log_object_prefix:
            Ref: LogObjectPrefix
          gzip_enabled:
            Ref: GzipEnabled
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: 'rate(2 minutes)'
      FunctionName: !Ref AWS::StackName
      Handler: lambda_function.lambda_handler
      Policies:
      - Statement:
        - Action:
          - s3:PutObject
          - s3:PutObjectTagging
          Effect: Allow
          Resource:
            Fn::Join: 
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3BucketForLogging 
              - '/*'
        - Action:
          - sqs:DeleteMessage
          - sqs:ReceiveMessage
          - sqs:GetQueueAttributes
          Effect: Allow
          Resource: 
            Fn::GetAtt: 
            - LogsQueue
            - Arn
        Version: '2012-10-17'
      Runtime: python3.8
      Timeout: 120
    Type: AWS::Serverless::Function
  LambdaLogsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Solution}"
      RetentionInDays: 90
Transform: AWS::Serverless-2016-10-31